### ISSUE TITLE
Unable to compile due to wrong jberet parent version

### ISSUE THREAD

**Issue by fstarred** [jberet/jberet-wildfly-samples#2]
Jberet parent version is neither distribuited as the parent project module and in maven central, therefore compilation fails.
Can you adjust project references ?

**Comment by chengfang** [comment]
I'll update the pom to use jberet-parent `1.4.0.Alpha`, which is available in maven central: https://search.maven.org/artifact/org.jberet/jberet-parent/1.4.0.Alpha/pom

**Comment by chengfang** [comment]
Just pushed the change https://github.com/jberet/jberet-wildfly-samples/commit/05e32170ec3a7ef3fb776b3de31b7ab55057928e

Project jberet-wildfly-samples should build and work fine now.

**Comment by fstarred** [comment]
I got this:
Failed to execute goal on project csv2json: Could not resolve dependencies for project org.jberet.samples:csv2json:war:1.4.0.Alpha-SNAPSHOT: Failed to collect dependencies at org.jberet:jberet-support:jar:1.4.0.Beta1: Failed to read artifact descriptor for org.jberet:jberet-support:jar:1.4.0.Beta1: Could not transfer artifact org.jberet:jberet-support:pom:1.4.0.Beta1

**Comment by chengfang** [comment]
jberet-support 1.4.0.Beta1 is already available at maven central (https://search.maven.org/artifact/org.jberet/jberet-support/1.4.0.Beta1/jar).  It could be a maven cache problem.  Can you build with `mvn -U` or delete .m2/repository/org/jberet/jberet-support?

**Comment by fstarred** [comment]
You are right, for some odd reasons it crashed.
Now it fails there:
Could not resolve dependencies for project org.jberet.samples:clusterInfinispan:war:1.4.0.Alpha-SNAPSHOT: Failed to collect dependencies at org.jberet:jberet-wildfly-cluster-infinispan:jar:1.3.0.Final: Failed to read artifact descriptor for org.jberet:jberet-wildfly-cluster-infinispan:jar:1.3.0.Final: Could not find artifact org.jberet:jberet-wildfly:pom:1.4.0.Alpha-SNAPSHOT in snapshots (https://integrazione.mgmt.infocert.it/artifactory/libs-snapshot) 

I already tried to looking for org.jberet:jberet-wildfly-cluster-infinispan:jar on maven central but with no result

**Comment by chengfang** [comment]
jberet-wildfly-cluster-infinispan is available https://search.maven.org/artifact/org.jberet/jberet-wildfly-cluster-infinispan/1.3.0.Final/jar

**Comment by fstarred** [comment]
Opened an issue in SO https://stackoverflow.com/questions/59406747/unable-to-download-artifactory-from-search-maven-org/59409492#59409492 however if I comment that dependency, at least it compile

**Comment by chengfang** [comment]
Just released version 1.3.1.Final of jberet-wildfly-* (jberet-wildfly, jberet-wildfly-cluster-jms, jberet-wildfly-cluster-servlet, jberet-wildfly-cluster-ejb, jberet-wildfly-cluster-infinispan), and updated dependency in jberet-wildfly-samples.  That should fix the problem.

**Comment by fstarred** [comment]
Finally it works, thank you
