### ISSUE TITLE
ItemReader doesn't throw ConstraintViolationException

### ISSUE THREAD

**Issue by fstarred** [jberet/jberet-wildfly-samples#3]
I'm testing bean validation on my custom entity.
According to _jberet-user-guide_, ItemReader should thrown **ConstraintViolationException** if entity doesn't pass validation; Actually item pass through **ItemWriter** and ConstratintViolation error is thrown only after the item's commit.
I tried also to include jberet-support but nothing changes.
Any hints?

**Comment by chengfang** [comment]
Application developers are responsible for implementing item reader, processor and writers, includig whether to perform bean validation or not and how. So if you want this validation, you will need to implement it in your item reader class.  All item reader classes from jberet-support already support and enable bean validation, for example, CsvItemReader, JsonItemReader, XmlItemReader, etc.

**Comment by chengfang** [comment]
See the source code for item reader for how bean validation is supported:

https://github.com/jberet/jberet-support/blob/master/src/main/java/org/jberet/support/io/ItemReaderWriterBase.java#L84

https://github.com/jberet/jberet-support/blob/master/src/main/java/org/jberet/support/io/JsonItemReader.java#L164

**Comment by fstarred** [comment]
Things are much clearer now, thank you
